export const INSERT_PRODUCT_CART = 'INSERT PRODUCT CART';
export const CLEAR_CART = 'CLEAR CART';
export const DELETE_ITEM_CART = 'DELETE ITEM CART';
export const INCREMENT_QNT_PRODUCT = 'INCREMENT QNT PRODUCT';
export const DECREMENT_QNT_PRODUCT = 'DECREMENT QNT PRODUCT'